import Head from "next/head";
import TimeContainer from "src/components/Time-Box";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="px-10 pt-5">
          <header>
            <h1>
              MY VISION. <strong>"Go abroad"</strong>
            </h1>
            <h2 className="flex gap-2">
              <span>#succecss</span>
              <span>#save money</span>
            </h2>
          </header>
          <section className="flex justify-between">
            <article>
              <h3>Plan</h3>
              <TimeContainer />
            </article>
            <article>
              <h3>Now</h3>
              <TimeContainer />
            </article>
            <article>
              <h3>Change</h3>
              <TimeContainer />
            </article>
          </section>
        </section>
      </main>
    </>
  );
}
