import Head from "next/head";
import { useState } from "react";
import NavBar from "src/components/Navbar";
import TimeContainer from "src/components/Time-Box";

export default function Home() {
  const [isFold, setIsFold] = useState(false);

  const handleClick = () => {
    setIsFold(!isFold);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex">
        <NavBar />
        <section className="relative">
          <header>
            <h1>GOAL</h1>
            <h3 className="flex gap-2">
              <div>#succecss</div>
              <div>#save money</div>
            </h3>
          </header>
          <section>
            <article>
              <TimeContainer />
            </article>
            <article></article>
            <article></article>
          </section>
        </section>
      </main>
    </>
  );
}
